apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-script
data:
  01-init.sql: |
    CREATE TABLE IF NOT EXISTS public.todos (
        id SERIAL PRIMARY KEY,
        title VARCHAR(255) NOT NULL,
        completed BOOLEAN DEFAULT FALSE
    );
    INSERT INTO todos (title) VALUES ('{{POD_NAMESPACE}} ready!') ON CONFLICT DO NOTHING;
