apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: exercises

resources:
# PostgreSQL
- postgresql-statefulset.yaml
- postgresql-service.yaml
- postgresql-configmap.yaml

# Ping-pong
#- ping-pong-deployment.yaml
- ping-pong-rollout.yaml                # ARGO rollout
- ping-pong-service.yaml
- cpu-analysis-template.yaml

# Log-output  
- log-output-deployment.yaml
- log-output-service.yaml
- log-output-configmap.yaml
